import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { adaptPromptSession } from "../src/optimization/index.js";
import { collectRuleSuggestions, createRuleSuggestion, detectUserRule } from "../src/rule-suggestions.js";

describe("rule suggestions", () => {
  it("detects a prescriptive user expectation", () => {
    const suggestion = detectUserRule("Update .env.example any time a new environment variable is needed.");
    expect(suggestion).toMatchObject({ source: "user", rule: "Update .env.example any time a new environment variable is needed." });
    expect(suggestion?.issueTitle).toContain("Enforce:");
  });

  it("accepts an agent-discovered rule and suppresses duplicates", () => {
    const signal = { source: "agent" as const, statement: "Secret values must never be passed as process arguments.", rationale: "The rule can be enforced by command-runner tests.", evidence: ["adapter review"] };
    expect(collectRuleSuggestions("Keep going.", [signal, signal])).toHaveLength(1);
    expect(createRuleSuggestion(signal).issueBody).toContain("generated by AI during triage");
  });

  it("rejects sensitive rule content", () => {
    expect(() => createRuleSuggestion({ source: "agent", statement: "Use alice@example.com in the rule.", rationale: "test" })).toThrow("sensitive content");
  });

  it("surfaces user and agent suggestions through session adaptation and persists a redacted artifact", async () => {
    const root = await mkdtemp(join(tmpdir(), "rule-suggestions-"));
    try {
      const input = {
        harnessRoot: root,
        sessionId: "session-1",
        traceId: "trace-1",
        projectKey: "harness",
        prompt: "Update .env.example whenever a new environment variable is needed.",
        resolvedContext: { id: "context-1", provenance: "trace-1:context", summary: "rule test" },
        events: [{ sessionId: "session-1", projectKey: "harness", mode: "implementation", skill: "test", event: "complete", durationMs: 1, result: "success" as const }],
        artifacts: [],
        feedback: [],
        observedState: [],
        ruleSignals: [{ source: "agent" as const, statement: "Secret values must never be passed as process arguments.", rationale: "A command-runner test can enforce this." }],
      };
      const result = await adaptPromptSession(input);
      expect(result.ruleSuggestions.map(({ source }) => source)).toEqual(["user", "agent"]);
      const persisted = await readFile(join(root, "docs/.scratch/setup/session-1/rule-suggestions.jsonl"), "utf8");
      expect(persisted).toContain(".env.example");
      expect(persisted).not.toContain("raw prompt");
      const repeated = await adaptPromptSession(input);
      expect(repeated.ruleSuggestions).toEqual([]);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
