import { createHash } from "node:crypto";
import { findSensitiveContent } from "./sensitive-content.js";

export type RuleSuggestionSource = "user" | "agent";

export interface RuleSignal {
  source: RuleSuggestionSource;
  statement: string;
  rationale: string;
  evidence?: readonly string[];
}

export interface RuleSuggestion {
  id: string;
  source: RuleSuggestionSource;
  rule: string;
  rationale: string;
  evidence: readonly string[];
  issueTitle: string;
  issueBody: string;
}

const prescriptiveLanguage = /\b(always|never|must|should|required|whenever|any time|every time|do not|don't)\b/i;
const enforcementLanguage = /\b(rule|policy|enforce|update|include|document|validate|check|prevent|require|needed)\b/i;

function text(value: string, label: string): string {
  if (typeof value !== "string" || value.trim() === "") throw new Error(`${label} must be non-empty`);
  const normalized = value.trim().replace(/\s+/g, " ");
  if (normalized.length > 500) throw new Error(`${label} exceeds 500 characters`);
  if (findSensitiveContent(`+${JSON.stringify(normalized)}`).length > 0) throw new Error(`${label} contains sensitive content`);
  return normalized;
}

function issueTitle(rule: string): string {
  return `Enforce: ${rule}`.slice(0, 120);
}

export function createRuleSuggestion(signal: RuleSignal): RuleSuggestion {
  const rule = text(signal.statement, "rule statement");
  const rationale = text(signal.rationale, "rule rationale");
  const evidence = (signal.evidence ?? []).map((item) => text(item, "rule evidence")).slice(0, 5);
  if (signal.source !== "user" && signal.source !== "agent") throw new Error("rule suggestion source is invalid");
  const id = `rule-${createHash("sha256").update(`${signal.source}\n${rule.toLowerCase()}`).digest("hex").slice(0, 16)}`;
  return {
    id,
    source: signal.source,
    rule,
    rationale,
    evidence,
    issueTitle: issueTitle(rule),
    issueBody: [
      "*This was generated by AI during triage.*",
      "",
      "## Proposed rule",
      "",
      rule,
      "",
      "## Why enforce it",
      "",
      rationale,
      "",
      "## Evidence",
      "",
      ...(evidence.length > 0 ? evidence.map((item) => `- ${item}`) : [`- Source: ${signal.source}`]),
    ].join("\n"),
  };
}

export function detectUserRule(prompt: string): RuleSuggestion | null {
  const statement = text(prompt, "user prompt");
  if (statement.endsWith("?") || !prescriptiveLanguage.test(statement) || !enforcementLanguage.test(statement)) return null;
  return createRuleSuggestion({
    source: "user",
    statement,
    rationale: "The user stated a repeatable expectation that can be checked or enforced by the harness.",
    evidence: ["User-stated expectation"],
  });
}

export function collectRuleSuggestions(prompt: string, signals: readonly RuleSignal[] = []): RuleSuggestion[] {
  const suggestions = [detectUserRule(prompt), ...signals.map(createRuleSuggestion)].filter((value): value is RuleSuggestion => value !== null);
  const unique = new Map<string, RuleSuggestion>();
  for (const suggestion of suggestions) {
    const key = suggestion.rule.toLowerCase().replace(/\s+/g, " ").trim();
    if (!unique.has(key)) unique.set(key, suggestion);
  }
  return [...unique.values()];
}
